### ISSUE TITLE
Add an option to automatically detect and build and add to the repository package dependencies that come from the AUR

### ISSUE THREAD

**Issue by Snogard** [tibor95/repokeeper#2]
as the title says.

**Comment by tibor95** [comment]
This is implemented in new 0.3.8 - it will try to build normal and build dependencies for packages that are to be built.
However, it still not install them so you will probably run repokeeper few times, after each run install what was built.

**Comment by Snogard** [comment]
awesome, thank you! I'll be testing the feature tomorrow, i'll let you know if everything works on my end.

**Comment by Snogard** [comment]
i can confirm that it works
